browser = Chrome
url = https://demoqa.com/
reportConfigPath = /src/test/resources/extent-config.xml
user = boby
timezone = IST
sampleImagePath = /src/test/resources/sampleFile.jpeg
failedrerunbackup.file.path = /src/test/resources/failedrerunbackup.txt
failedrerun.file.path = /src/test/resources/failedrerun.txt
allureReports.folder.path = /test-reports/AllureReports
backupBase.folder.path = /test-reports/AllureReportsBackup