browser = chrome
url = https://demoqa.com/
reportConfigPath = E:\Programming\workspace\SeleniumCucumberMBDD2\extent-config.xml
user = boby
timezone = IST
failedrerunbackup.file.path = E:/Programming/workspace/SeleniumCucumberMBDD2/src/test/resources/failedrerunbackup.txt
failedrerun.file.path = E:/Programming/workspace/SeleniumCucumberMBDD2/src/test/resources/failedrerun.txt
test = E:/Programming/workspace/SeleniumCucumberMBDD2/extent-config.xml