browser = Chrome
url = https://demoqa.com/
browserWindowsPageURL = https://demoqa.com/browser-windows
browserWindowsSamplePageURL = https://demoqa.com/sample
bookStoreLoginPageURL = https://demoqa.com/login
reportConfigPath = /src/test/resources/extent-config.xml
user = boby
username = BobyBrahmam
password = TestBoby@108
timezone = IST
cucumberReportsScreenshots = /cucumber-reports/screenshots/
sampleImagePath = /src/test/resources/sampleFile.jpeg
failedrerunbackup.file.path = /src/test/resources/failedrerunbackup.txt
failedrerun.file.path = /src/test/resources/failedrerun.txt
allureReports.folder.path = /test-reports/AllureReports
backupBase.folder.path = /test-reports/AllureReportsBackup